spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
      auto-offset-reset: latest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
